/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordleRouteImport } from './routes/wordle'
import { Route as LoveRouteImport } from './routes/love'
import { Route as IndexRouteImport } from './routes/index'

const WordleRoute = WordleRouteImport.update({
  id: '/wordle',
  path: '/wordle',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveRoute = LoveRouteImport.update({
  id: '/love',
  path: '/love',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/love': typeof LoveRoute
  '/wordle': typeof WordleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/love': typeof LoveRoute
  '/wordle': typeof WordleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/love': typeof LoveRoute
  '/wordle': typeof WordleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/love' | '/wordle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/love' | '/wordle'
  id: '__root__' | '/' | '/love' | '/wordle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoveRoute: typeof LoveRoute
  WordleRoute: typeof WordleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordle': {
      id: '/wordle'
      path: '/wordle'
      fullPath: '/wordle'
      preLoaderRoute: typeof WordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love': {
      id: '/love'
      path: '/love'
      fullPath: '/love'
      preLoaderRoute: typeof LoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoveRoute: LoveRoute,
  WordleRoute: WordleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
