/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GridIndexRouteImport } from './routes/grid/index'
import { Route as GridSizeRouteImport } from './routes/grid/size'
import { Route as GridExportRouteImport } from './routes/grid/export'
import { Route as GridEditRouteImport } from './routes/grid/edit'
import { Route as GridColorsRouteImport } from './routes/grid/colors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridIndexRoute = GridIndexRouteImport.update({
  id: '/grid/',
  path: '/grid/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridSizeRoute = GridSizeRouteImport.update({
  id: '/grid/size',
  path: '/grid/size',
  getParentRoute: () => rootRouteImport,
} as any)
const GridExportRoute = GridExportRouteImport.update({
  id: '/grid/export',
  path: '/grid/export',
  getParentRoute: () => rootRouteImport,
} as any)
const GridEditRoute = GridEditRouteImport.update({
  id: '/grid/edit',
  path: '/grid/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GridColorsRoute = GridColorsRouteImport.update({
  id: '/grid/colors',
  path: '/grid/colors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grid/colors': typeof GridColorsRoute
  '/grid/edit': typeof GridEditRoute
  '/grid/export': typeof GridExportRoute
  '/grid/size': typeof GridSizeRoute
  '/grid': typeof GridIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grid/colors': typeof GridColorsRoute
  '/grid/edit': typeof GridEditRoute
  '/grid/export': typeof GridExportRoute
  '/grid/size': typeof GridSizeRoute
  '/grid': typeof GridIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grid/colors': typeof GridColorsRoute
  '/grid/edit': typeof GridEditRoute
  '/grid/export': typeof GridExportRoute
  '/grid/size': typeof GridSizeRoute
  '/grid/': typeof GridIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grid/colors'
    | '/grid/edit'
    | '/grid/export'
    | '/grid/size'
    | '/grid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grid/colors'
    | '/grid/edit'
    | '/grid/export'
    | '/grid/size'
    | '/grid'
  id:
    | '__root__'
    | '/'
    | '/grid/colors'
    | '/grid/edit'
    | '/grid/export'
    | '/grid/size'
    | '/grid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GridColorsRoute: typeof GridColorsRoute
  GridEditRoute: typeof GridEditRoute
  GridExportRoute: typeof GridExportRoute
  GridSizeRoute: typeof GridSizeRoute
  GridIndexRoute: typeof GridIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/': {
      id: '/grid/'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/size': {
      id: '/grid/size'
      path: '/grid/size'
      fullPath: '/grid/size'
      preLoaderRoute: typeof GridSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/export': {
      id: '/grid/export'
      path: '/grid/export'
      fullPath: '/grid/export'
      preLoaderRoute: typeof GridExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/edit': {
      id: '/grid/edit'
      path: '/grid/edit'
      fullPath: '/grid/edit'
      preLoaderRoute: typeof GridEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/colors': {
      id: '/grid/colors'
      path: '/grid/colors'
      fullPath: '/grid/colors'
      preLoaderRoute: typeof GridColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GridColorsRoute: GridColorsRoute,
  GridEditRoute: GridEditRoute,
  GridExportRoute: GridExportRoute,
  GridSizeRoute: GridSizeRoute,
  GridIndexRoute: GridIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
